# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26e074d26d95046aeddb141ccf6d555a97f657370cda1640ac1a3875e9b1a65f5bd130467425f0f7a9f310cc7d7fcf013f133c8e4119b1652f584b4c6323af8b

test:
  secret_key_base: 76f0a3e2464f1418d172be27e77cf9f38c73a76f6bc8593ef5239e2bff719f9b42494995c1916b1e965acf87119f2fbd476ac2078a956eb20d550e2de33f2d67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
